# Generated by Django 4.2.5 on 2023-10-25 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendances_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
