# Generated by Django 4.2.5 on 2023-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendances_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='attendance_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
