# Generated by Django 4.2.5 on 2023-09-13 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
