# Generated by Django 4.2.5 on 2023-09-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_end_date_courses_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='num_of_student',
            field=models.IntegerField(default=0),
        ),
    ]
