# Generated by Django 4.2.5 on 2023-10-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_usercourse_alter_courses_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
            ),
        ),
    ]
