# Generated by Django 4.2.5 on 2023-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
