# Generated by Django 4.2.5 on 2023-10-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_newuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
